---

- name: Ensure iptables packages are installed
  ansible.builtin.apt:
    name:
      - iptables
      - iptables-persistent
    state: "{{ 'latest' if apt_update_latest else 'present' }}"
    update_cache: "{{ apt_update_cache }}"
    cache_valid_time: "{{ apt_cache_valid_time }}"
  notify:
    - save iptables rules
    - save ip6tables rules
  tags:
    - iptables
    - update
