---

- hosts: all
  become: true
  gather_facts: true
  roles:
    - role: pipx
    - role: pipx
      vars:
        pipx_package: ansible
    - role: pipx
      vars:
        pipx_packages:
          - black
          - httpie
    - role: pipx
      vars:
        pipx_package: poetry
        pipx_packages:
          - uvicorn
          - virtualenv
