---

# Host Configuration

- import_playbook: hostname.yaml
- import_playbook: iptables.yaml
- import_playbook: netplan.yaml
- import_playbook: packages.yaml
- import_playbook: ssh.yaml
- import_playbook: time.yaml
- import_playbook: reboot.yaml

# Application Deployment

## Stage 1

- import_playbook: certificate.yaml
- import_playbook: docker.yaml
- import_playbook: keepalived.yaml
- import_playbook: kubectl.yaml
- import_playbook: pipx.yaml
- import_playbook: postgresql.yaml
- import_playbook: unbound.yaml

## Stage 2

- import_playbook: docker_compose.yaml
- import_playbook: pihole.yaml
